# nom workflow
name: "Déploiement auto push branche main"

# Trigger
on: 
  push: 
    branches: 
      - main

# créer instance Ubuntu
jobs:
  creation-vm:
    name: "création d'une instance de Ubuntu"
    runs-on: ubuntu-latest
    
    steps: 
      # ajout de la clé privé de l'utilisateur de déploiement
      - name: "création de jeu de clé SSH pour l'utilisateur de déploiement"
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: | 
          # création dossier /.ssh
          mkdir -p ~/.ssh

          # ajout de la clé dans le fichier id_rsa
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # configuration de l'hôte dans known_hosts
          ssh-keyscan -t rsa -p $SSH_PORT $SSH_HOST >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

# Connexion SSH à la VM
      - name: "Connexion SSH à la VM"
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: | 
          ssh -p $SSH_PORT $SSH_USER@$SSH_HOST 'cd /var/www/html/BIBYdex && git fetch && git pull'
